//! # Acton-AI: Agentic AI Framework
//!
//! An agentic AI framework where each agent is an actor, leveraging acton-reactive's
//! supervision, pub/sub, and fault tolerance to create resilient, concurrent AI systems.
//!
//! ## Architecture
//!
//! - **Agent**: Individual AI agents with reasoning loops
//! - **LLM Provider**: Manages streaming LLM API calls with rate limiting
//! - **Tool Registry**: Registers and executes tools via supervised child actors
//! - **MCP Client**: Consumes tools from external Model Context Protocol servers,
//!   one supervised actor per connection (see [`mcp`])
//! - **Memory Store**: Persistence via Turso/libSQL
//! - **Checkpoints**: Resumable turns — see [`checkpoint`]
//!
//! ## Quick Start (High-Level API)
//!
//! The simplest way to use acton-ai is via the `ActonAI` facade:
//!
//! ```rust,ignore
//! use acton_ai::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), ActonAIError> {
//!     let runtime = ActonAI::builder()
//!         .app_name("my-app")
//!         .ollama("qwen2.5:7b")
//!         .launch()
//!         .await?;
//!
//!     runtime
//!         .prompt("What is the capital of France?")
//!         .system("Be concise.")
//!         .on_token(|t| print!("{t}"))
//!         .collect()
//!         .await?;
//!
//!     println!();
//!     Ok(())
//! }
//! ```
//!
//! ## Advanced Usage (Low-Level API)
//!
//! For full control over the actor system:
//!
//! ```rust,ignore
//! use acton_ai::prelude::*;
//!
//! #[tokio::main]
//! async fn main() {
//!     let mut app = ActonApp::launch_async().await;
//!
//!     let provider = LLMProvider::spawn(&mut app, "default", ProviderConfig::ollama("qwen2.5:7b")).await;
//!
//!     let mut agent = Agent::create(&mut app);
//!     let agent_handle = agent.start().await;
//!     agent_handle.send(InitAgent::default()).await;
//!
//!     app.shutdown_all().await.unwrap();
//! }
//! ```

pub mod accounting;
pub mod agent;
pub mod audit;
pub mod checkpoint;
pub mod cli;
pub mod config;
pub mod conversation;
pub mod error;
pub mod extract;
pub mod facade;
pub mod fips;
pub mod instructions;
pub mod introspection;
pub mod llm;
pub mod logging;
pub mod mcp;
pub mod memory;
pub mod messages;
pub mod policy;
pub mod prompt;
pub mod stream;
pub mod telemetry;
pub mod tools;
pub mod types;

pub mod skills;

/// Re-export of the [`schemars`] crate that generated schemas are built with.
///
/// [`PromptBuilder::extract`](crate::prompt::PromptBuilder::extract) requires
/// its target type to implement [`schemars::JsonSchema`]. Normally you add
/// `schemars` to your own `Cargo.toml` and derive it there; this re-export
/// exists so the version in use is discoverable and so documentation can link
/// to it. `JsonSchema` is deliberately **not** in the [`prelude`] — the name
/// collides too easily with application types.
pub use schemars;

/// Re-export of the [`serde_json`] crate the framework speaks JSON with.
///
/// Tool arguments, tool results, and schemas are all [`serde_json::Value`].
/// Code generated by [`#[tool]`](macro@tool) reaches `serde_json` through
/// this path rather than assuming the downstream crate has its own
/// dependency on it — which is what lets a crate use the macro with
/// `acton-ai` as its only dependency.
pub use serde_json;

/// Turns an `async fn` into a [`Tool`](crate::tools::Tool) implementation.
///
/// Requires the `derive` feature (enabled by default). See the
/// [macro's own documentation](macro@tool) for the full contract.
#[cfg(feature = "derive")]
pub use acton_ai_macros::tool;

// Support code for macro expansions. Public because generated code in
// downstream crates has to reach it; `#[doc(hidden)]` and double-underscored
// because nothing else should. Exempt from semver.
#[doc(hidden)]
#[path = "private.rs"]
pub mod __private;

/// Prelude module for convenient imports
pub mod prelude {
    // High-level API (recommended for most use cases)
    pub use crate::accounting::{
        dollars_to_microusd, Budget, BudgetConfig, BudgetDecision, BudgetEvent, BudgetScope,
        BudgetStatus, CheckBudget, CostBreakdown, GetUsage, ModelPricing, ModelUsage, PricingTable,
        ProviderUsage, ScopeStatus, UsageSnapshot, DEFAULT_WARN_AT_PERCENT,
    };
    pub use crate::audit::{
        default_audit_path, verify_chain, AppendReceipt, AuditConfig, AuditDecision,
        AuditDurability, AuditEntry, AuditEntryKind, AuditHealth, AuditHealthChanged,
        AuditHealthState, AuditOutcome, ChainBreak, ChainBreakKind, ChainHead, ContextSource,
        InvocationRecord, Redactor, TurnAuditOutcome, TurnRecord, DEFAULT_REDACT_PATTERNS,
        GENESIS_HASH,
    };
    pub use crate::checkpoint::{
        CheckpointError, CheckpointErrorKind, CheckpointRecord, CheckpointSink, CheckpointStatus,
        ResumePlan, TurnFingerprint, TurnInputs,
    };
    pub use crate::config::{
        ActonAIConfig, ActonAIDefaults, AuditFileConfig, BudgetFileConfig,
        CircuitBreakerFileConfig, IntrospectionFileConfig, McpServerConfig, NamedProviderConfig,
        PricingFileConfig, RateLimitFileConfig, ToolPolicyFileConfig,
    };
    pub use crate::conversation::{
        ChatConfig, Conversation, ConversationBuilder, StreamToken, DEFAULT_SYSTEM_PROMPT,
    };
    pub use crate::error::{ActonAIError, ActonAIErrorKind, ProviderAttempt};
    pub use crate::extract::STRUCTURED_OUTPUT_TOOL;
    pub use crate::facade::{ActonAI, ActonAIBuilder, DEFAULT_PROVIDER_NAME};
    pub use crate::fips::{install_crypto_provider, is_fips_build};
    pub use crate::instructions::{
        AgentInstructions, InstructionLayer, InstructionScope, InstructionsError,
    };
    pub use crate::introspection::{AdmissionGate, AdmissionState, IntrospectionConfig};
    pub use crate::mcp::{McpError, McpErrorKind, McpTools};
    pub use crate::policy::{
        ApprovalDecision, ApprovalFuture, ApprovalHookFn, Decider, DenialReason,
        ToolClassification, ToolInvocation, ToolPolicy, TurnCounts,
    };
    pub use crate::stream::{CollectedResponse, StreamAction, StreamContext, StreamHandler};

    // Low-level API (for advanced use cases)
    pub use crate::agent::{
        Agent, AgentConfig, AgentState, DelegatedTask, DelegatedTaskState, DelegationTracker,
        IncomingTaskInfo, InitAgent,
    };
    pub use crate::error::AgentError;
    pub use crate::llm::{
        AnthropicClient, CheckHealth, CircuitBreakerConfig, FailoverEvent, InitLLMProvider,
        LLMClient, LLMClientResponse, LLMError, LLMErrorKind, LLMEventStream, LLMProvider,
        LLMStreamEvent, OpenAIClient, ProviderConfig, ProviderHealth, ProviderType,
        RateLimitConfig, RetryConfig, SamplingParams, DEFAULT_COOLDOWN, DEFAULT_FAILURE_THRESHOLD,
    };
    pub use crate::logging::{
        init_and_store_logging, init_journald_logging, journald_layer, mark_subscriber_installed,
        LogLevel, LoggingConfig, LoggingError, LoggingErrorKind,
    };
    pub use crate::memory::{
        AgentStateSnapshot, CheckpointList, CheckpointLoaded, CheckpointSaved, CompactionConfig,
        CompactionOutcome, CompactionRecord, CompactionThreshold, ContextStats, ContextWindow,
        ContextWindowConfig, ContextWindowData, ContextWindowResponse, CreateSession,
        DeleteCheckpoint, DeleteSession, Embedding, EmbeddingError, EmbeddingProvider,
        GetContextWindow, InitMemoryStore, KeepRecentTurns, ListCheckpoints, ListSessions,
        LoadCheckpoint, LoadMemories, MemoriesLoaded, Memory, MemorySearchResults, MemoryStore,
        MemoryStoreMetrics, MemoryStoreMetricsSnapshot, MemoryStored, OperationCompleted,
        PersistenceConfig, PersistenceError, ResolveSession, SaveCheckpoint, ScoredMemory,
        SearchMemories, SessionCreated, SessionInfo, SessionList, SessionResolved, StoreMemory,
        StubEmbeddingProvider, TouchSession, TruncationStrategy, UpdateSessionMetadata,
    };
    pub use crate::messages::*;
    pub use crate::tools::builtins::{
        BuiltinExecutor, BuiltinTools, UpdatePlanTool, UpdatePlanToolActor,
    };
    pub use crate::tools::sandbox::SandboxedExecution;
    pub use crate::tools::{
        plan_from_tool_result, Plan, PlanError, PlanNote, PlanStep, PlanStepStatus, PlanStepTitle,
        PlanTextError, RawPlanStep, Tool, ToolConfig, ToolDefinition, ToolError, ToolErrorKind,
        ToolExecutorTrait, ToolFuture, UPDATE_PLAN_TOOL,
    };

    /// The [`#[tool]`](macro@crate::tool) attribute macro.
    ///
    /// Gated on the `derive` feature so that
    /// `--no-default-features` builds do not pull in a proc-macro crate.
    #[cfg(feature = "derive")]
    pub use crate::tool;
    pub use crate::types::{
        AgentId, CheckpointId, ConversationId, CorrelationId, InvalidTaskId, MemoryId, MessageId,
        TaskId, ToolName, TrailId, TurnId,
    };

    // Re-export acton-reactive prelude
    pub use acton_reactive::prelude::*;

    // Agent Skills
    pub use crate::skills::{LoadedSkill, SkillInfo, SkillRegistry, SkillsError};
    pub use crate::tools::builtins::{
        skill_tool_names, spawn_skill_tool_actors, ActivateSkillTool, ActivateSkillToolActor,
        ListSkillsTool, ListSkillsToolActor,
    };
}
