//! Tool system for the Acton-AI framework.
//!
//! This module provides the infrastructure for tool registration and execution:
//!
//! - **Tool Trait & Executors**: The [`Tool`] trait (usually generated by the
//!   `#[tool]` attribute macro) and the [`ToolExecutorTrait`] /
//!   [`BoxedToolExecutor`] executor shapes
//! - **Tool Actors**: Per-agent tool actors for isolated tool execution
//! - **Built-ins**: Ready-made filesystem/shell/web tools in [`builtins`]
//! - **Sandbox**: Interface for sandboxed code execution (ProcessSandbox backend)
//!
//! ## Architecture
//!
//! ### Prompt-Loop Tools (Recommended)
//!
//! Tools offered to the model are plain specs — a definition plus an executor —
//! carried by the prompt loop itself. Register them:
//!
//! - per prompt, with [`PromptBuilder::tool`](crate::prompt::PromptBuilder::tool) /
//!   [`with_tool`](crate::prompt::PromptBuilder::with_tool) /
//!   [`add_tool`](crate::prompt::PromptBuilder::add_tool);
//! - per conversation, with
//!   [`ConversationBuilder::with_tool`](crate::conversation::ConversationBuilder::with_tool);
//! - runtime-wide, with
//!   [`ActonAIBuilder::with_tool`](crate::facade::ActonAIBuilder::with_tool) /
//!   [`with_tool_executor`](crate::facade::ActonAIBuilder::with_tool_executor) /
//!   [`add_tool`](crate::facade::ActonAIBuilder::add_tool).
//!
//! Whichever way a tool arrives, it executes on the same path as the
//! built-ins — behind the tool-approval policy gate and onto the audit trail
//! when those are configured.
//!
//! ### Per-Agent Tool Actors
//!
//! ```text
//! +-------------------------------------------------------------+
//! |                      Agent Actor                             |
//! |                                                              |
//! |  tool_handles: HashMap<String, ActorHandle>                 |
//! |                                                              |
//! +-------------------------------------------------------------+
//!                            |
//!                            | supervises
//!                            v
//! +-------------------------------------------------------------+
//! |                   Tool Actor (per tool)                      |
//! |                                                              |
//! |  ExecuteToolDirect --> execute(args) --> ToolActorResponse  |
//! |                                                              |
//! +-------------------------------------------------------------+
//! ```
//!
//! ## Usage
//!
//! ### Runtime-Wide Registration
//!
//! ```rust,ignore
//! use acton_ai::prelude::*;
//!
//! let runtime = ActonAI::builder()
//!     .anthropic_from_env()
//!     .with_tool(calculator_definition(), |args| async move {
//!         Ok(serde_json::json!({"result": calculate(&args)?}))
//!     })
//!     .launch()
//!     .await?;
//! ```
//!
//! ### Per-Agent Tools
//!
//! ```rust,ignore
//! use acton_ai::prelude::*;
//!
//! // Configure agent with specific tools
//! let config = AgentConfig::new("You are helpful.")
//!     .with_tools(&["read_file", "write_file", "glob"]);
//!
//! // Tools are spawned automatically when the agent initializes
//! ```

pub mod actor;
pub mod builtins;
pub mod definition;
pub mod error;
pub mod sandbox;
pub mod security;
pub mod tool_trait;

// Re-exports
pub use crate::messages::ToolDefinition;
pub use actor::{
    ExecuteToolDirect, ToolActor, ToolActorResponse, ToolExecutor as ToolExecutorAsync,
};
pub use builtins::BuiltinExecutor;
pub use definition::{BoxedToolExecutor, ToolConfig, ToolExecutionFuture, ToolExecutorTrait};
pub use error::{ToolError, ToolErrorKind};
pub use sandbox::{
    Sandbox, SandboxExecutionFuture, SandboxFactory, SandboxFactoryFuture, SandboxedExecution,
};
pub use security::{PathValidationError, PathValidator};
pub use tool_trait::{Tool, ToolFuture};

// Stub implementation is only available in tests (security concern in production)
#[cfg(test)]
pub use sandbox::{StubSandbox, StubSandboxFactory};
